### PR TITLE
README includes required peer dependences

### PR DESCRIPTION
**Pull request by fruchtose**
👓  @curioussavage

We have updated project peer dependencies, but the documentation was not up-to-date.

### CODE REVIEW

**Comment by curioussavage** [comment]
per in person convo - can we check if installing with these deps errors encountered when running local mweb against this?

edit: disregard this.

**Comment by curioussavage** [comment]
🐟

**Comment by fruchtose** [comment]
@curioussavage I updated the PR. Notably, I rolled back the versions of React and ReactDOM to match closer to what `reddit-mobile` uses.

@birakattack It's occurred to me that we have a "duplicate dependency" issue going on between `node-platform` and `reddit-mobile`. IMO it doesn't make sense for both packages to import React/DOM separately. This opens us up to issues where the two packages use different versions of the same library. For many packages, minor differences can be OK. However, since React is such a complex beast, using two different versions of it across the client and server can result in many bugs.

I think we should consider exporting the most version sensitive dependencies from `node-platform`, and then import them in `reddit-mobile`. For instance, we could have a file `deps.js` like this:

```
import * as ReactDOM from 'react-dom';
export { ReactDOM };
export { default as React } from 'react';
```

And then in `reddit-mobile`, we would `import { React } from `@r/platform/deps;` or some similar statement. How does that sound? The answer isn't relevant to this PR, but it's a discussion worth having.

**Comment by curioussavage** [comment]
The changes proposed would definitely need to be passed by @nramadas and/or @schwers and probably tech leads of the other teams that use platform.

**Pull request merged**
